FROM golang:1.24 AS build
WORKDIR /go/src
COPY {{apiPath}} ./{{apiPath}}
COPY main.go .
COPY go.sum .
COPY go.mod .
COPY .env .env
RUN echo "\n\nIS_BUILD=true" >> .env

ENV CGO_ENABLED=0

RUN go build -o {{packageName}} .

FROM gcr.io/distroless/static AS runtime
ENV GIN_MODE=release
COPY --from=build /go/src/{{packageName}} ./
COPY --from=build /go/src/.env ./
COPY ./api/openapi.yaml ./api/openapi.yaml

EXPOSE 8080/tcp
ENTRYPOINT ["./{{packageName}}"]
